name: Minimal Test Workflow

on:
  workflow_dispatch:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  minimal-test:
    name: Minimal Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Display environment
        run: |
          echo "Testing minimal workflow functionality"
          echo "Repository: ${{ github.repository }}"
          echo "Event: ${{ github.event_name }}"
          pwd
          ls -la