name: PowerShell Tests (Fork-Friendly)

# Streamlined PowerShell testing workflow for psPAS module
# Features essential 3-tier caching and fork-friendly operation

on:
  push:
  pull_request:
  workflow_dispatch:


jobs:
  test:
    name: PowerShell Tests on Windows
    runs-on: windows-latest
    timeout-minutes: 25
    
    defaults:
      run:
        shell: pwsh
        
    permissions:
      contents: read
      actions: read
      
    env:
      PSModulePath: ${{ github.workspace }}/psPAS;$env:PSModulePath
      POWERSHELL_TELEMETRY_OPTOUT: 1
      TEST_RESULTS_PATH: TestResults
    
    steps:
      # Repository checkout with retry
      - name: Checkout Repository
        uses: actions/checkout@v4
        timeout-minutes: 5
        with:
          fetch-depth: 1
          

      # Cache PowerShell dependencies (Pester and PSScriptAnalyzer)
      - name: Cache PowerShell Dependencies
        uses: actions/cache@v4
        with:
          path: C:\Users\runneradmin\Documents\PowerShell\Modules
          key: powershell-modules-${{ runner.os }}-pester-psscriptanalyzer
          restore-keys: |
            powershell-modules-${{ runner.os }}-

      # Install dependencies
      - name: Install Dependencies
        timeout-minutes: 15
        run: |
          Write-Host "📦 Installing PowerShell dependencies..."
          
          $modules = @('Pester', 'PSScriptAnalyzer')
          
          foreach ($module in $modules) {
            Write-Host "Installing $module..."
            Install-Module -Name $module -Force -SkipPublisherCheck -Scope CurrentUser
            Write-Host "✅ $module installed successfully"
          }


      # Import psPAS module
      - name: Import psPAS Module
        timeout-minutes: 10
        run: |
          Write-Host "📥 Importing psPAS module..."
          
          # Import with force and error handling
          Import-Module "${{ github.workspace }}/psPAS/psPAS.psd1" -Force -ErrorAction Stop
          
          # Verify import
          $module = Get-Module -Name psPAS
          if (-not $module) {
            throw "psPAS module not loaded after import"
          }
          
          Write-Host "✅ psPAS module imported successfully"
          Write-Host "   Version: $($module.Version)"
          Write-Host "   Exported Functions: $($module.ExportedFunctions.Count)"


      # Run tests with error handling
      - name: Run Tests
        timeout-minutes: 22
        continue-on-error: true
        run: |
          Write-Host "🧪 Running Pester tests..."
          
          # Import psPAS module for this session
          Write-Host "📥 Importing psPAS module for test session..."
          Import-Module "${{ github.workspace }}/psPAS/psPAS.psd1" -Force -ErrorAction Stop
          
          try {
            # Create test results directory
            if (-not (Test-Path "TestResults")) {
              New-Item -ItemType Directory -Path "TestResults" -Force | Out-Null
            }
            
            # Configure Pester
            $config = New-PesterConfiguration
            $config.Run.Path = 'Tests'
            $config.Run.PassThru = $true
            $config.Run.Exit = $false
            $config.TestResult.Enabled = $true
            $config.TestResult.OutputPath = "TestResults\TestResults.xml"
            $config.TestResult.OutputFormat = 'NUnitXml'
            $config.Output.Verbosity = 'Normal'
            
            # Run tests
            $result = Invoke-Pester -Configuration $config
            
            Write-Host "📊 Test Results:"
            Write-Host "   Total: $($result.TotalCount)"
            Write-Host "   Passed: $($result.PassedCount)" 
            Write-Host "   Failed: $($result.FailedCount)"
            Write-Host "   Skipped: $($result.SkippedCount)"
            
            if ($result.FailedCount -gt 0) {
              Write-Warning "Some tests failed, but continuing for fork-friendly operation"
            }
            
          }
          catch {
            Write-Error "Test execution failed: $_"
            # Create placeholder results file for artifact upload
            if (-not (Test-Path "TestResults")) {
              New-Item -ItemType Directory -Path "TestResults" -Force | Out-Null
            }
            "Test execution failed: $_" | Out-File "TestResults\error.log"
          }


      # Upload test results
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        timeout-minutes: 5
        with:
          name: test-results-${{ github.run_number }}
          path: |
            TestResults/
            *.log
          retention-days: 30
          if-no-files-found: warn

